name: GitHub Package Registry Publish Workflow

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - v*

jobs:
  publish-gpr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@cybearl"
          always-auth: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Publish to GitHub Package Registry
        working-directory: ./dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish GitHub release from tag (if 'push' is a tag)
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
